# Generated by Django 3.0.4 on 2020-03-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200328_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
